PR-2211 Add llapi_path2fid support
whamcloud/integrated-manager-for-lustre pull request #2212
Opened 2020-09-02 21:10 UTC by beevans

Signed-off-by: Ben Evans <beevans@whamcloud.com>

2020-09-03 12:57 UTC, utopiabound requested changes

2020-09-03 12:57 UTC, utopiabound commented on liblustreapi/src/lib.rs
> +		Ok(f) => {
(same as above)

2020-09-05 13:23 UTC, jgrund commented
Looks like this code needs `rustfmt` run on it.

2020-09-05 13:28 UTC, jgrund commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
I think we should add a `SymbolNotFound` variant to `LiblustreError` so it's clear to the caller what went wrong.

2020-09-08 13:17 UTC, beevans commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
I'm just following the pattern of fid2path

2020-09-08 13:19 UTC, jgrund commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
yeah, looks like that should be updated as well.

2020-09-08 13:20 UTC, beevans commented on liblustreapi/src/lib.rs
> +	let mut page: Vec<u8> = vec![0; std::mem::size_of::<u8>() * 16];
done

2020-09-08 13:21 UTC, beevans commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
So open a ticket to add SymbolNotFound to LiblustreError and handle all the cases in here?

2020-09-08 13:24 UTC, jgrund commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
New ticket and fix in here is fine.

2020-09-08 13:27 UTC, beevans commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
#2226 created

2020-09-08 15:09 UTC, utopiabound submitted a review, later dismissed

2020-09-08 17:14 UTC, jgrund commented
This needs rebase on latest master due to: https://github.com/whamcloud/integrated-manager-for-lustre/pull/2223

2020-09-08 19:25 UTC, jgrund commented on liblustreapi/src/lib.rs
> +            let rc = match self.lib.get(b"llapi_path2fid\0") {
PR: https://github.com/whamcloud/integrated-manager-for-lustre/pull/2228

2020-09-08 19:26 UTC, jgrund approved these changes

2020-09-09 13:26 UTC, utopiabound approved these changes

2020-09-09 13:28 UTC, merged