Hotpool v2 Imlementation
whamcloud/integrated-manager-for-lustre pull request #2241
Opened 2020-09-14 13:40 UTC by utopiabound

Core logic to create Hotpool v2.

Fixes #1464

2020-09-14 14:00 UTC, utopiabound commented
This is dependent on:
* #2178

2020-09-14 14:12 UTC, jgrund commented on chroma_core/models/filesystem.py
> +        return groups.values()
This fn isn't accurate as it doesn't account for bans.

2020-09-14 14:16 UTC, jgrund commented on chroma_api/hotpool.py
> +from collections import defaultdict
The API should be part of graphql instead.

2020-09-14 14:20 UTC, jgrund commented on chroma_core/services/job_scheduler/job_scheduler.py
> +    def create_hotpool(self, hotpool_data):
This should be a graphql endpoint.

2020-09-14 14:26 UTC, jgrund requested changes
There are a few things in here that should leverage graphql instead.

2020-09-17 12:57 UTC, jgrund requested changes
Python hotpool api still needs removal

2020-09-17 13:01 UTC, jgrund commented on chroma_core/services/job_scheduler/job_scheduler.py
> +    def create_hotpool(self, hotpool_data):
Unresolving as current patch still contains change.

2020-11-04 15:33 UTC, jgrund commented on iml-api/src/graphql/mod.rs
> +    /// Fetch the list of known targets
Update docs to describe params

2020-11-04 15:59 UTC, jgrund commented on iml-wire-types/src/lib.rs
> +    pub cold_id: i32,
Update to `cold_pool_name`

2020-11-04 15:59 UTC, jgrund commented on iml-wire-types/src/lib.rs
> +    pub hot_id: i32,
Update to `hot_pool_name`

2022-01-11 15:12 UTC, closed without merging