Extract command polling logic to it's own crate
whamcloud/integrated-manager-for-lustre pull request #2251
Opened 2020-09-18 16:53 UTC by jgrund

This patch extracts the command polling logic to it's own crate.
It doesn't use any feature flags, and does not duplicate the polling
logic.

The internal behavior is delegated to a mpsc channel, where the caller
can decide how to process completions and updates.

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

2020-09-18 17:06 UTC, ip1981 approved these changes

2020-09-21 07:58 UTC, mkpankov approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/whamcloud/integrated-manager-for-lustre/2251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nlinker)



<!-- Sent from Reviewable.io -->

2020-09-21 08:19 UTC, mkpankov requested changes
We need `wait_for_cmds_success` here as well.

2020-09-21 11:38 UTC, nlinker approved these changes
I guess we can land it and then move 
```
pub async fn wait_for_cmds_success(
    cmds: &[Command],
    tx: Option<mpsc::UnboundedSender<Progress>>,
) -> Result<Vec<Command>, ...> {...}
```
to `iml-command-utils/src/lib.rs`

2020-09-22 13:11 UTC, jgrund commented
> We need wait_for_cmds_success here as well. 

Looks like it's been added in your patch.

2020-09-22 13:15 UTC, mkpankov approved these changes

2020-09-22 18:27 UTC, merged