Add snapshot retention ops to CLI
whamcloud/integrated-manager-for-lustre pull request #2267
Opened 2020-09-23 15:33 UTC by ip1981

Signed-off-by: Igor Pashev <pashev.igor@gmail.com>

2020-09-23 15:34 UTC, ip1981 commented on iml-api/src/graphql.rs
>          keep_num: i32,
This is inconsistently optional here and there.

2020-09-24 14:03 UTC, jgrund commented on iml-graphql-queries/src/snapshot.rs
> +            lat_run: lastRun
```suggestion
            last_run: lastRun
```

2020-09-24 14:04 UTC, jgrund requested changes
There is a typo for the `SnapshotRetentionPolicies` query.

2020-09-24 16:19 UTC, jgrund approved these changes

2020-09-24 16:22 UTC, merged