GH-2268 Update the limit param in graphql api's
whamcloud/integrated-manager-for-lustre pull request #2269
Opened 2020-09-23 19:35 UTC by johnsonw

Fixes #2268.

Currently, the limit param allows you to specify a limit when retrieving items back from an API call. This is a numeric value that can be passed in but in some cases, we may want all results. To address this, postress allows us to pass in ALL instead of a numeric value, which is effectively the same as not passing a limit at all. Update all of the graphql API endpoints such that if None is passed in it will pass ALL to the LIMIT clause in the query. This will allow us to get all entries without modifying the existing api.

Signed-off-by: johnsonw <wjohnson@whamcloud.com>

2020-09-23 19:38 UTC, ip1981 commented on iml-api/src/graphql.rs
> +            limit.map(|x| x.to_string()).unwrap_or("ALL".to_string()) as String
```suggestion
            limit.map(|x| x.to_string()).unwrap_or_else(|| "ALL".to_string()) as String
```

2020-09-23 19:39 UTC, johnsonw commented on iml-api/src/graphql.rs
> +            limit.map(|x| x.to_string()).unwrap_or("ALL".to_string()) as String
sure, makes sense. I'll update.

2020-09-24 13:28 UTC, jgrund requested changes
Comments need updating as well, as they still say they default to 20.

2020-09-24 13:30 UTC, ip1981 commented on iml-api/src/graphql.rs
> +                .unwrap_or_else(|| "ALL".to_string()) as String
`as String` really needed?

2020-09-24 13:35 UTC, johnsonw commented on iml-api/src/graphql.rs
> +                .unwrap_or_else(|| "ALL".to_string()) as String
It required the cast.

2020-09-24 14:06 UTC, jgrund commented on iml-api/src/graphql.rs
> +        limit(description = "paging limit, defaults to All"),
Maybe: 

```suggestion
        limit(description = "optional paging limit, defaults to all rows"),
```

2020-09-24 16:57 UTC, jgrund approved these changes

2020-09-24 17:22 UTC, ip1981 approved these changes

2020-09-24 18:35 UTC, merged