agent: Return cloned resources with index from crm mon output
whamcloud/integrated-manager-for-lustre pull request #2370
Opened 2020-11-09 01:31 UTC by utopiabound

Account for index in wait_resource and remove cruft code.

Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>

2020-11-09 19:08 UTC, jgrund approved these changes

2020-11-09 19:29 UTC, jgrund requested changes
Looks like some of the snapshot test output has changed.

2020-11-11 15:01 UTC, jgrund approved these changes

2020-11-11 19:52 UTC, johnsonw approved these changes

2020-11-11 19:56 UTC, merged