Add Basic formatting pre-commit check
whamcloud/integrated-manager-for-lustre pull request #2417
Opened 2020-12-04 21:05 UTC by utopiabound

Formatting check supports both rust and python code.
Doesn't add the weight of doing a cargo build on a system
that doesn't support it.

Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>

2020-12-04 21:06 UTC, jgrund requested changes
This will conflict with rusty-hook, which also installs a pre-commit hook for rust.

2020-12-04 21:23 UTC, utopiabound commented
It's an alternative, since I don't commit from a build machine in my work-flow.

2020-12-04 21:25 UTC, jgrund commented
> It's an alternative, since I don't commit from a build machine in my work-flow. 

Let's not document it then. I don't want to have competing pre-commit hooks in the readme

2020-12-06 14:35 UTC, jgrund approved these changes

2020-12-06 14:38 UTC, merged